"""empty message

Revision ID: 4538558651ad
Revises: 
Create Date: 2019-06-10 19:38:17.877493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4538558651ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movierank01', sa.Integer(), nullable=True),
    sa.Column('movierank02', sa.Integer(), nullable=True),
    sa.Column('movierank03', sa.Integer(), nullable=True),
    sa.Column('movierank04', sa.Integer(), nullable=True),
    sa.Column('movierank05', sa.Integer(), nullable=True),
    sa.Column('movierank06', sa.Integer(), nullable=True),
    sa.Column('movierank07', sa.Integer(), nullable=True),
    sa.Column('movierank08', sa.Integer(), nullable=True),
    sa.Column('movierank09', sa.Integer(), nullable=True),
    sa.Column('movierank10', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pearson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_moviename', sa.String(length=300), nullable=True),
    sa.Column('movierank01', sa.String(length=120), nullable=True),
    sa.Column('movierank02', sa.String(length=120), nullable=True),
    sa.Column('movierank03', sa.String(length=120), nullable=True),
    sa.Column('movierank04', sa.String(length=120), nullable=True),
    sa.Column('movierank05', sa.String(length=120), nullable=True),
    sa.Column('movierank06', sa.String(length=120), nullable=True),
    sa.Column('movierank07', sa.String(length=120), nullable=True),
    sa.Column('movierank08', sa.String(length=120), nullable=True),
    sa.Column('movierank09', sa.String(length=120), nullable=True),
    sa.Column('movierank10', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pearson')
    op.drop_table('movies')
    # ### end Alembic commands ###
